# Generated by Django 4.0.1 on 2022-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=50, null=True)),
                ('varsity', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
